### ISSUE TITLE
harpoon crashes on Apple ._ files

### ISSUE THREAD

**Issue by vidjya** [evilhero/harpoon#15]
When adding a torrent from a mac with the harpoon watch folder mounted as a smb share, harpoon seems to stop at apple resources forks (._filename.torrent).

There's no way to disable the creation of these files when moving a file to the share.

Here's the entry from the log:

Traceback (most recent call last):
  File "./lib/apscheduler/scheduler.py", line 476, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "./harpoon.py", line 1258, in Scanner
    torrent_info = tinfo.main()
  File "/home/user/harpoon/harpoon/rtorrent.py", line 172, in main
    loadit = self.client.load_torrent(self.filepath, self.label, self.start, self.applylabel, self.basedir)
  File "/home/user/harpoon/harpoon/torrent/clients/rtorrent.py", line 112, in load_torrent
    torrent = self.conn.load_torrent(filepath, verify_load=True)
  File "/home/user/harpoon/lib/rtorrent/__init__.py", line 167, in load_torrent
    tp = TorrentParser(torrent)
  File "/home/user/harpoon/lib/rtorrent/lib/torrentparser.py", line 54, in __init__
    assert isinstance(self._torrent_decoded, dict), "Invalid torrent file."

As far as I can tell, it does not go past that point.

**Comment by vidjya** [comment]
Scratch this, I think this was due to the specific torrent file I was using. I removed that one and added another one without issue. It seems that the torrent file I was using was already in rtorrent and it didn't really deal with that.

**Comment by evilhero** [comment]
If the torrent file was already in rtorrent when you added it, it should just simply report back some of the stats and then try to harpoon it back locally and perform the post-processing as required.

Odds are it was trying to actually load the ```._filename.torrent``` file as a legitimate file (because it looks for anything with a ```.torrent``` extension in the watch dirs when monitoring), and obviously it wasn't. Should be an easy fix to ignore those types of files going forward.

**Comment by vidjya** [comment]
To be clear, I thought it was stopping on the dotbar file. It probably wasn't because I dropped another torrent into that folder and macos automatically creates a dotbar. That torrent worked fine, however. Loaded and downloaded to my local server.

In terms of downloading an existing torrent, it wasn't doing that. It creates a hash file and then stops. I tried that a couple of times with the daemon, but had no issue downloading it manually with harpoon.

**Comment by vidjya** [comment]
Harpoon's definitely having some issues with dotbar files. I'm having some trouble recreating it due to other stability issues (possibly OS related?), but I can confirm that after deleting a stray dotbar file, the waiting torrent started up on the next run.
