### ISSUE TITLE
Initiating

### ISSUE THREAD

**Issue by Aquenon** [evilhero/harpoon#8]
I'm probably going to regret posting this because it's probably going to be obvious when it's answered. But how do you get this to run? I've made a copy of conf.ini.sample to get conf.ini. I've filled it in. I've tried python harpoon.py, I've tried python harpoonshot.py, I've tried python harpoon.py --(different options). I always get:

Traceback (most recent call last):
  File "harpoon.py", line 28, in <module>
    import requests
ImportError: No module named requests

What's staring in the face is where it says Linux only. But Mac is UNIX based just like Linux, so I'm hoping that's not it.

**Comment by evilhero** [comment]
We didn't include the requests library, but you can install it easily enough ```pip install requests``` would install requests on the local system.

We'll add it into the lib/ folder going forward.

**Comment by Aquenon** [comment]
ok, I did that. Now it gets further, then I get this new error:

azeroth:harpoon scott$ python harpoon.py
Traceback (most recent call last):
  File "harpoon.py", line 55, in <module>
    logger.initLogger(logpath)
  File "/Applications/Python Scripts/harpoon/harpoon/logger.py", line 35, in initLogger
    file_handler = handlers.RotatingFileHandler(filename, maxBytes=1000000, backupCount=5)
  File "/usr/local/Cellar/python@2/2.7.14_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/Cellar/python@2/2.7.14_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/Cellar/python@2/2.7.14_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python@2/2.7.14_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/opt/harpoon/logs/harpoon.log'
azeroth:harpoon scott$ 

I tried to 'pip install logger' thinking it was the same kind of error as before, but that didn't work.

**Comment by evilhero** [comment]
Ugh - you're acing this eh?

Have to add a check for that (never hit it), but you need to create the /opt/harpoon/logs directory and then it won't throw that error.

**Comment by Aquenon** [comment]
Well, I'm giving this another go. lol.

I tried this again tonight.  Updated Harpoon.  It told me I don't have requests again.  Installed that.  It needed nose and tornado, so I installed those.  Ran Python again.  New error.  I thought I had things handled with Hazel automation with a manual download initiation.  But that starts moving stuff before it's finished downloading on large files.  So, I decided to try this again.  If the post-processing into Plex works, then I can possibly get this set up like I need.

Any ideas?

Also, if I get this working, will it only work when it initiates it?  Or will it monitor everything on the seedbox and download it as it finishes?

Thanks,
Scott


**Error:**
azeroth:harpoon scott$ python harpoon.py
Traceback (most recent call last):
  File "harpoon.py", line 54, in <module>
    os.mkdir(logpath)
OSError: [Errno 2] No such file or directory: '/opt/harpoon/logs'
azeroth:harpoon scott$ 



In case you need it, the configuration file is as follows:

[general]
APPLYLABEL=true
DEFAULTDIR=/Volumes/Working/Downloads
TORRENTFILE_DIR=/Volumes/Working/Torrents
LOGPATH=/opt/harpoon/logs
MULTIPLE_SEEDBOXES=false
TORRENTCLIENT=rtorrent
LCMD_PARALLEL=
LCMD_SEGMENTS=

[rtorrent]
RTORR_HOST=********.seedbox.io
RTORR_PORT=
RTORR_USER=********
RTORR_PASSWD=********************
RPC_URL=/RPC/17618/
AUTHENTICATION=basic
SSL=true
VERIFY_SSL=true
STARTONLOAD=true

[post-processing]
PP_HOST= ********.seedbox.io
PP_SSHPORT=443
PP_USER= ********
PP_PASSWD= ********
PP_BASEDIR=/home/********/files

[label_directories]
TVDIR=/Volumes/Working/Downloads/Series
MUSICDIR=/Volumes/Working/Downloads/Music
MOVIEDIR=/Volumes/Working/Downloads/Movies
XXXDIR=/Volumes/Working/Downloads/Porn
COMICSDIR=/Volumes/Working/Downloads/Comics
BOOKDIR=/Volumes/Working/Downloads/Books

[sonarr]
URL=
APIKEY=
SONARR_LABEL=

[sickrage]
URL=
APIKEY=
DELETE=
FORCE_REPLACE=
FORCE_NEXT=
PROCESS_METHOD=
IS_PRIORITY=
FAILED=
TYPE=
SICKRAGE_LABEL=

[radarr]
URL=
APIKEY=
RADARR_LABEL=
KEEP_ORIGINAL_FOLDERNAMES=false

[mylar]
URL=
APIKEY=
MYLAR_LABEL=

[lidarr]
URL=
APIKEY=
LIDARR_LABEL=

[lazylibrarian]
URL=
APIKEY=
LAZYLIBRARIAN_LABEL=

[plex]
PLEX_UPDATE=false
PLEX_HOST_IP=http://127.0.0.1
PLEX_HOST_PORT=32400
PLEX_LOGIN=********@********.com
PLEX_PASSWORD=********
PLEX_TOKEN=
